spring:
  config:
    activate:
      on-profile: homolog

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: HOMOLOG
    password: root
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api/spring

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs

jwt:
  key: dGVzdC1zZWNyZXQta2V5
  expiration: 1h

viacep:
  url: https://viacep.com.br/ws

project:
  database: "Oracle"
  environment-name: "Homologation"
