spring:
  application:
    name: "@project.name@"

  profiles:
    active: homolog

  jpa:
    open-in-view: true

  flyway:
    enabled: false

project:
  name: "@project.name@"
  version: "@project.version@"
